server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.first.kotlin.po

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gavin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      # 连接池最大阻塞等待时间，负值表示没有限制
      max-wait: -1
      min-idle: 0
    timeout: 0

